apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier-email
  template:
    metadata:
      labels:
        app: notifier-email
    spec:
      containers:
        - name: notifier-email
          image: notifier_service
          imagePullPolicy: IfNotPresent
          env:
            - name: CHANNELS_SERVER_URL
              value: "channels:8080"
            - name: CHANNEL_TYPE
              value: "email"
            - name: RABBIT_URI
              value: "amqp://guest:guest@rabbitmq:5672/"

