apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-slack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier-slack
  template:
    metadata:
      labels:
        app: notifier-slack
    spec:
      containers:
        - name: notifier-slack
          image: notifier_service
          imagePullPolicy: IfNotPresent
          env:
            - name: CHANNELS_SERVER_URL
              value: "channels:8080"
            - name: CHANNEL_TYPE
              value: "slack"
            - name: RABBIT_URI
              value: "amqp://guest:guest@rabbitmq:5672/"

