apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: data
            - mountPath: /var/log/rabbitmq
              name: log
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rabbitmq-data
        - name: log
          persistentVolumeClaim:
            claimName: rabbitmq-log
